### ISSUE TITLE
`AMIP with diagnostic EDMF and io` case fails on`ClimaCoupler - CPU/GPU Benchmarks` pipeline

### ISSUE THREAD

**Issue by sriharshakandala** [CliMA/ClimaCoupler.jl#1104]
`AMIP with diagnostic EDMF and io` case fails on`ClimaCoupler - CPU/GPU Benchmarks` pipeline.
Please see https://buildkite.com/clima/climacoupler-cpu-gpu-benchmarks/builds/207#_ for the detailed error.

cc: @juliasloan25 , @szy21

**Comment by juliasloan25** [comment]
It looks like a bunch of agents got lost in that build, but after re-trying everything works except for some output file access. Can we close this issue?

**Comment by sriharshakandala** [comment]
Can you please post the link with a successful build here?
If its a temporary issue and works fine after restarting, we can close the issue.
Thanks for looking into this!

**Comment by juliasloan25** [comment]
In the same link you mention in the issue description, all of the simulations pass and only the table creation step fails because it can't find all the output files. This is likely because of our output directory syncing, which we know is flaky for re-tried runs. https://buildkite.com/clima/climacoupler-cpu-gpu-benchmarks/builds/207

**Comment by juliasloan25** [comment]
Benchmarks are all working now. See https://buildkite.com/clima/climacoupler-cpu-gpu-benchmarks/builds/209
